bucket_name = "terraform-action-testbucket-2"
bucket_name1 = "terraform-action-testbucket-3"
bucket_name2 = "terraform-action-testbucket-4"
location = "us-central1"
project_id = "terraform-test-384414"
region = "us-central1"
#credentials = "terraform-test-384414-8ae5aeb96ebf.json"